export enum TaskStatusEnum {
  CREATED = 'CREATED',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  STARTED = 'STARTED',
  FINISHED = 'FINISHED',
  COMPLETED = 'COMPLETED',
  ERRORED = 'ERRORED',
  FAILED = 'FAILED',
}
