const MASTER_PK_PREFIX = 'MASTER'
const SETTING_SK_PREFIX = 'MASTER_SETTING'
const DATA_SK_PREFIX = 'MASTER_DATA'
const MASTER_COPY_SK_PREFIX = 'MASTER_COPY'

export {
  DATA_SK_PREFIX,
  MASTER_COPY_SK_PREFIX,
  MASTER_PK_PREFIX,
  SETTING_SK_PREFIX,
}
