export const EVENT_METADATA = '__event__'
export const EVENT_HANDLER_METADATA = '__eventHandler__'
export const EVENT_FACTORY_METADATA = '__eventFactory__'
export const DATA_SYNC_HANDLER_METADATA = '__dataSyncHandler__'
export const ROLE_METADATA = '__allowedRoles__'
