name: Run test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
      - main

jobs:
  unit_tests:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Build packages
        run: npm run build

      - name: Run Unit Tests
        run: npm run test

  e2e_tests:
    name: E2e Test For Core package
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build test
        run: npx lerna run build:test --scope=@mbc-cqrs-serverless/core

      - name: Run e2e Tests
        run: npx lerna run test:e2e --scope=@mbc-cqrs-serverless/core

      - uses: actions/upload-artifact@v4
        name: 'upload artifact'
        if: success() || failure()
        with:
          name: my-artifacts
          path: ./packages/core/test/scripts/*.out.txt